apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talentlink-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"  # Allow 10MB file uploads
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - talentlink-erfan.nl
      secretName: myapp-tls

  rules:
    - host: talentlink-erfan.nl
      http:
        paths:
          # FRONTEND - Flutter web SPA
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

          # BACKEND MICROSERVICES
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 5000

          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 5000

          - path: /api/jobs
            pathType: Prefix
            backend:
              service:
                name: job-service
                port:
                  number: 5000

          - path: /api/applications
            pathType: Prefix
            backend:
              service:
                name: application-service
                port:
                  number: 5000

          - path: /api/cv
            pathType: Prefix
            backend:
              service:
                name: cv-service
                port:
                  number: 5000

          - path: /api/matching
            pathType: Prefix
            backend:
              service:
                name: matching-service
                port:
                  number: 5000

          - path: /api/notifications
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 5000

          # KEYCLOAK
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080

          # RABBITMQ MANAGEMENT
          - path: /rabbitmq
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
