apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  namespace: default
  labels:
    app: job-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: job-service
          image: ghcr.io/erfanalizada/job-service:57acba87b03303f774c58602ebd02beb43e03afd
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: jobsdb-secret
                  key: DATABASE_URL
            - name: KEYCLOAK_URL
              value: "http://keycloak.default.svc.cluster.local:8080/auth"
            - name: KEYCLOAK_REALM
              value: "talentlink"
            - name: KEYCLOAK_CLIENT_ID
              value: "job-service"

          readinessProbe:
            httpGet:
              path: /api/jobs/test-db
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 15

          livenessProbe:
            httpGet:
              path: /api/jobs/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
