      containers:
        - name: matching-service
          image: ghcr.io/erfanalizada/matching-service:4035dc6a16bae2d29cefbc59f02970443ea23c8b
          ports:
            - containerPort: 5004
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: matchingdb-secret
                  key: DATABASE_URL

            - name: RABBITMQ_URL
              value: "amqp://admin:adminpass123@rabbitmq:5672/%2F"
            - name: KEYCLOAK_URL
              value: "https://talentlink-erfan.nl/auth"
            - name: KEYCLOAK_REALM
              value: "talentlink"
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-secret
                  key: GEMINI_API_KEY
                  optional: true
            - name: PORT
              value: "5004"

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /api/matching/health
              port: 5004
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /api/matching/health
              port: 5004
            initialDelaySeconds: 30
            periodSeconds: 10
