apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: job=ghcr.io/erfanalizada/job-service
    argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  source:
    repoURL: https://github.com/erfanalizada/talentlink.git
    targetRevision: main
    path: k8s/backend/job
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
