apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matching-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: matching=ghcr.io/erfanalizada/matching-service
    argocd-image-updater.argoproj.io/matching.pull-secret: pullsecret:argocd/ghcr-creds
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/erfanalizada/talentlink.git
    targetRevision: main
    path: k8s/backend/matching
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
